name: Docker Build

on:
  workflow_dispatch:
    inputs:
      os: { type: string, default: 'ubuntu-24.04', description: "Name of the OS that jobs run on" }
      out-docker-image: { type: string, default: 'fortify', description: "Name of output docker image" }
      out-docker-latest: { type: boolean, default: false, description: "If build docker image with the latest tag" }
  workflow_call:
    inputs:
      os: { type: string, required: true, description: "Name of the OS that jobs run on" }
      out-docker-image: { type: string, default: 'fortify', description: "Name of output docker image" }
      out-docker-latest: { type: boolean, default: false, description: "If build docker image with the latest tag" }

jobs:
  build-and-upload:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 30
          fetch-tags: true

      - uses: i3ash/setup-cidoer@v1
        with: { ref: '1.0' }

      - name: Prepare
        shell: bash
        run: |
          source cidoer.sh
          do_workflow_job prepare
          echo "ArtifactTag=${ARTIFACT_TAG:-}" >> $GITHUB_ENV

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clean Docker environment
        run: |
          docker system prune -af
          docker builder prune -af

      - name: Build and Push Docker Images - Debian
        if: env.ArtifactTag != 'v0'
        working-directory: '${{ github.workspace }}'
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.out-docker-image }}
          ARTIFACT_TAG: ${{ env.ArtifactTag }}-debian
          LATEST_TAG: ${{ inputs.out-docker-latest }}
        run: |
          source cidoer.sh
          do_workflow_job docker_debian

      - name: Build and Push Docker Images - Alpine
        if: env.ArtifactTag != 'v0'
        working-directory: '${{ github.workspace }}'
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.out-docker-image }}
          ARTIFACT_TAG: ${{ env.ArtifactTag }}-alpine
          LATEST_TAG: ${{ inputs.out-docker-latest }}
        run: |
          source cidoer.sh
          do_workflow_job docker_alpine

      - name: Build and Push Docker Images - Minimal
        if: env.ArtifactTag != 'v0'
        working-directory: '${{ github.workspace }}'
        env:
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.out-docker-image }}
          ARTIFACT_TAG: ${{ env.ArtifactTag }}
          LATEST_TAG: ${{ inputs.out-docker-latest }}
        run: |
          source cidoer.sh
          do_workflow_job docker_minimal

## --------------------
## 241206
